### ISSUE TITLE
Delay on touch event

### ISSUE THREAD

**Issue by makam92** [SmartToolFactory/Compose-Colorful-Sliders#3]
Would it be possible to add a delay parameter for the touch event so it doesn't instantly change the value of the slider when a touch event is registered? Would make it easier in a scrollable view to activate the scroll rather than flinging the values on the slider. The [motion event lib](https://github.com/SmartToolFactory/Compose-Extended-Gestures) you're using has something called  delayAfterDownInMillis: Long = 0L maybe that does the trick?

**Comment by SmartToolFactory** [comment]
Hi. I'm a little bit busy at the moment. Would you mind forking the project and trying with that param. It's likely to work but if you are still not satisfied with the result i can update with drag gesture which checks for a threshold in px before commencing onDrag and add a snap for steps. I will update with both soon and plan to add color intervals such as color1 (0.3*width), color2(0.4*width) so on. Maybe i add animation for changing slider thumb to rect on touch but not available at the moment. I'm building an image cropper

**Comment by makam92** [comment]
Sure no problem. Will let you know how it goes.

**Comment by makam92** [comment]
did not work to just implement that parameter so probably have to go some other route.

**Comment by SmartToolFactory** [comment]
Thanks. I will update it with drag on next update. Instead o starting with onDown. Delay probably didn't work because

https://github.com/SmartToolFactory/Compose-Colorful-Sliders/blob/e987dca4d893a09a43ed0dcc170128707c7f9f5c/slider/src/main/java/com/smarttoolfactory/slider/ColorfulSlider.kt#L217

i'm invoking value change when pointer is down. I will take quick look tomorrow and do an hot-fix with drag.

**Comment by SmartToolFactory** [comment]
Delay probably didn't work because of

https://github.com/SmartToolFactory/Compose-Colorful-Sliders/blob/e987dca4d893a09a43ed0dcc170128707c7f9f5c/slider/src/main/java/com/smarttoolfactory/slider/ColorfulSlider.kt#L217

i'm invoking value change when pointer is down. I will take quick look tomorrow and do a hot-fix with drag if delay and removing down event is not enough
