### ISSUE TITLE
Size is too big

### ISSUE THREAD

**Issue by arguswaikhom** [SmartToolFactory/Compose-Colorful-Sliders#7]
After adding this package, the APK size increased by 6MB. Is there any way to optimize the size / divide into multiple smaller module or anything?

**Comment by SmartToolFactory** [comment]
I'm only using Compose libraries as you can see in dependencies. Would you mind forking and removing if any dependencies that are not required. Maybe icons and icons extended libraries add this size. If that's the case i can update with vector drawables instead of getting them via  Icons.Default/Filled.X
